language: node_js
node_js:
- 8.9.4
addons:
  ssh_known_hosts: 165.227.197.233
before_deploy:
- openssl aes-256-cbc -K $encrypted_9876fe5253b3_key -iv $encrypted_9876fe5253b3_iv
  -in deploy.enc -out deploy -d
- eval "$(ssh-agent -s)"
script:
  - bash ./script.sh
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR teste@165.227.197.233:/var/www/files
  on:
    branch: master
