language: node_js
node_js:
- 8.9.4
services: mongodb
cache:
  yarn: true
  directories:
  - node_modules
addons:
  ssh_known_hosts: 165.227.197.233
script:
- yarn test
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_9876fe5253b3_key -iv $encrypted_9876fe5253b3_iv
  -in deploy.enc -out /tmp/deploy -d
